services:
  - type: web
    name: job-portal-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: DB_URL
        value: <your_mongodb_atlas_connection_string>
      - key: CLOUDINARY_API_KEY
        value: <your_cloudinary_api_key>
      - key: CLOUDINARY_API_SECRET
        value: <your_cloudinary_api_secret>
      - key: CLOUDINARY_CLOUD_NAME
        value: <your_cloudinary_cloud_name>
      - key: JWT_SECRET_KEY
        value: <generate_a_secure_random_string>
      - key: JWT_EXPIRE
        value: 7d
      - key: COOKIE_EXPIRE
        value: 7
      - key: FRONTEND_URL
        value: https://your-frontend-app.vercel.app
